import random
import sqlite3

connection = sqlite3.connect("banco.db")
cursor = connection.cursor()
cursor.execute("create table alunos (matricula text, nome text, ano integer)")

nomes = [
    "Helena",
    "Alice",
    "Laura",
    "Maria Alice",
    "Sophia",
    "Manuela",
    "Maitê",
    "Liz",
    "Cecília",
    "Isabella",
    "Luísa",
    "Heloísa",
    "Eloá",
    "Júlia",
    "Ayla",
    "Maria Luísa",
    "Isis",
    "Elisa",
    "Antonella",
    "Valentina",
    "Maya",
    "Maria Júlia",
    "Aurora",
    "Lara",
    "Maria Clara",
    "Lívia",
    "Esther",
    "Giovanna",
    "Sarah",
    "Maria Cecília",
    "Lorena",
    "Beatriz",
    "Luna",
    "Olivia",
    "Maria Helena",
    "Mariana",
    "Isadora",
    "Melissa",
    "Maria",
    "Catarina",
    "Lavinia",
    "Alicia",
    "Maria Eduarda",
    "Agatha",
    "Ana Liz",
    "Yasmin",
    "Emanuelly",
    "Ana Clara",
    "Clara",
    "Miguel",
    "Arthur",
    "Gael",
    "Théo",
    "Heitor",
    "Ravi",
    "Davi",
    "Bernado",
    "Noah",
    "Gabriel",
    "Samuel",
    "Pedro",
    "Anthony",
    "Isaac",
    "Benício",
    "Benjamin",
    "Matheus",
    "Lucas",
    "Joaquim",
    "Nicolas",
    "Lucca",
    "Lorenzo",
    "Henrique",
    "João Miguel",
    "Rafael",
    "Henry",
    "Murilo",
    "Levi",
    "Guilherme",
    "Vicente",
    "Felipe",
    "Bryan",
    "Matteo",
    "Bento",
    "João Pedro",
    "Pietro",
    "Leonardo",
    "Daniel",
    "Gustavo",
    "Pedro Henrique",
    "João Lucas",
    "Emanuel",
    "João",
    "Caleb",
    "Davi Lucca",
    "Antônio",
    "Eduardo",
    "Enrico",
    "Caio",
    "José"
]

sobrenomes = [
    "Da Silva",
    "Pereira",
    "Ferreira",
    "Silva",
    "De Souza",
    "Santos",
    "Ribeiro",
    "Martins",
    "Barbosa",
    "Vieira",
    "Fernandes",
    "Costa",
    "De Souza",
    "De Lima",
    "Moreira",
    "Da Costa",
    "Mendes",
    "Araujo",
    "Teixeira",
    "Almeida",
    "Machado",
    "Nascimento",
    "Bezerra",
    "Dos Santos",
    "Alves",
    "De Oliveira",
    "De Jesus",
    "Soares",
    "Lopes",
    "Souza",
    "Lima",
    "Batista",
    "Dias",
    "Do Nascimento",
    "Nunes",
    "De Almeida",
    "Carvalho",
    "Cardoso",
    "Marques",
    "Ramos",
    "Rocha",
    "De Araujo",
    "Sousa"
    "Borges",
    "Aparecido",
    "Pinheiro",
    "Andrade",
    "Leite",
    "Nogueira",
    "Da Cruz",
    "Tavares",
    "De Freitas",
    "Pires",
    "Miranda",
    "Freitas",
    "Dos Reis",
    "Do Carmo",
    "Moraes",
    "De Melo",
    "Viana",
    "Moura"
]

anos = [2019,2020,2021,2022,2023,2024]
anos = random.choices(anos, k=50)

alunos = [[
    str(ano)+str(random.randint(1000,9999)),
    f"{random.choice(nomes)} {random.choice(sobrenomes)}",
    ano
    ] for ano in anos
]

cursor.executemany("insert into alunos values (?,?,?)", alunos)

connection.close()
